export default labelStyle = {
  fontFamily:
    '-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji',
  color: ' #333',
  hyphens: 'manual',
  letterSpacing: 'normal',
  listStyle: 'none',
  outline: 'none',
  position: 'static',
  textDecoration: 'none',
  textIndent: '0',
  textShadow: 'none',
  textTransform: 'none',
  width: 'auto',
  visibility: 'visible',
  overflow: 'visible',
  boxShadow: 'none',
  border: '0',
  verticalAlign: 'middle',
  background: 'none',
  height: 'auto',
  boxSizing: ' border-box',
  display: 'block',
  fontSize: '13px',
  float: 'none',
  fontWeight: '400',
  lineHeight: '1.3',
  margin: ' 4px 0 0',
  padding: '0',
};
